
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 906437
	#The name of the modpack
	modpackName = "MUNGCRAFT: REQUIEM"
	#The version of the modpack
	modpackVersion = "3.0.4"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

