
[general]
	#Puts all the added items into a new Every Compat tab instead of their own mod tabs. Be warned that if disabled it could cause some issue with some mods that have custom tabs
	creative_tab = true
	#Allows the mod to try to remap and convert other blocks and items from other compat mods that have been uninstalled from one world. This was made so one can uninstall such mods seamlessly having their blocks converted into Evety Compat counterparts
	remap_other_mods = false
	#Clears out and remaps all blocks registered by this mod belonging to uninstalled wood types to air or oak wood
	remap_self = true
	#Makes dynamic assets that are generated depend on loaded resource packs. Turn off to make them just use vanilla assets
	assets_depend_on_loaded_packs = true

[leaves_type]

	[leaves_type.minecraft]
		oak = true
		spruce = true
		birch = true
		jungle = true
		acacia = true
		dark_oak = true
		azalea = true
		flowering_azalea = true

	[leaves_type.dynamictrees]
		spruce = true
		oak_undergrowth = true
		oak = true
		jungle_undergrowth = true
		jungle = true
		flowering_azalea = true
		dark_oak = true
		birch = true
		azalea = true
		acacia = true

	[leaves_type.dtterralith]
		spruce_twiglet = true
		spruce_tall_conifer = true
		spruce_sparse = true
		spruce_short_conifer = true
		spruce_round = true
		spruce_poplar = true
		spruce_moonlight = true
		spruce_bush = true
		oak_yellow_conifer = true
		oak_twiglet = true
		oak_tall_conifer = true
		oak_sparse = true
		oak_scruffy_tall_conifer = true
		oak_scruffy = true
		oak_kapok = true
		oak_conifer = true
		jungle_windswept = true
		jungle_sparse = true
		jungle_sakura = true
		jungle_jacaranda = true
		flowering_azalea_oasis = true
		flowering_azalea_mahogany = true
		flowering_azalea_canopy = true
		dark_oak_sakura_bush = true
		dark_oak_sakura = true
		dark_oak_red_maple = true
		dark_oak_red_conifer = true
		dark_oak_red_azalea = true
		dark_oak_orange_conifer = true
		dark_oak_maple = true
		dark_oak_jacaranda = true
		dark_oak_canopy_mirage = true
		dark_oak_canopy = true
		dark_oak_blue_conifer = true
		dark_oak_ancient = true
		birch_windswept = true
		birch_twilight = true
		birch_sparse = true
		birch_short_conifer = true
		birch_scruffy_conifer = true
		birch_poplar = true
		birch_conifer = true
		azalea_oasis = true
		azalea_mahogany = true
		azalea_ebony = true
		azalea_canopy = true
		acacia_windswept = true
		acacia_twiglet = true
		acacia_sparse = true
		acacia_poplar = true
		acacia_kapok = true
		acacia_deciduous = true
		acacia_conifer = true
		acacia_bush = true
		acacia_amethyst = true

	[leaves_type.quark]
		blue_blossom = true
		lavender_blossom = true
		orange_blossom = true
		pink_blossom = true
		yellow_blossom = true
		red_blossom = true

	[leaves_type.dtquark]
		warm_blossom = true
		sweet_blossom = true
		sunny_blossom = true
		serene_blossom = true
		frosty_blossom = true
		fiery_blossom = true

	[leaves_type.architects_palette]
		twisted = true

	[leaves_type.wildbackport]
		mangrove = true

	[leaves_type.twigs]
		bamboo = true

	[leaves_type.croptopia]
		cinnamon = true

	[leaves_type.twilightforest]
		twilight_oak = true
		canopy = true
		mangrove = true
		dark = true
		time = true
		transformation = true
		mining = true
		sorting = true
		thorn = true
		beanstalk = true
		rainbow_oak = true

	[leaves_type.dtphc2]
		tropical_pine = true
		rubber = true
		paperbark = true
		papaya = true
		maple = true
		eucalyptus = true
		date = true
		coconut = true
		cinnamon = true
		banana = true

[wood_type]

	[wood_type.minecraft]
		oak = true
		spruce = true
		birch = true
		jungle = true
		acacia = true
		dark_oak = true
		crimson = true
		warped = true

	[wood_type.domum_ornamentum]
		cactus = true
		green_cactus = true

	[wood_type.quark]
		azalea = true
		blossom = true

	[wood_type.architects_palette]
		twisted = true

	[wood_type.wildbackport]
		mangrove = true

	[wood_type.twigs]
		bamboo = true

	[wood_type.darkerdepths]
		petrified = true

	[wood_type.born_in_chaos_v1]
		scorched = true

	[wood_type.twilightforest]
		twilight_oak = true
		canopy = true
		mangrove = true
		dark = true
		time = true
		transformation = true
		mining = true
		sorting = true

