
#General mod settings
[general]
	#Mobs enhanced by zombie awareness
	enhancedMobs = ["minecraft:zombie", "minecraft:husk", "minecraft:creeper", "minecraft:skeleton", "minecraft:stray", "minecraft:witch", "minecraft:zombie_villager", "monsterplus:crystal_zombie", "monsterplus:swamp_zombie", "monsterplus:glow_skeleton", "born_in_chaos_v1:door_knight"]

